In [ ]:
# Import libraries
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


texts = [
    "I love this movie",
    "This film is amazing",
    "Very good acting",
    "Excellent story",
    "I hate this movie",
    "Terrible film",
    "Very boring story",
    "Worst acting ever"
]

# Labels
# 1 = Positive
# 0 = Negative

labels = np.array([1, 1, 1, 1, 0, 0, 0, 0])


#words to numbers
tokenizer = Tokenizer()

# Learn vocabulary
tokenizer.fit_on_texts(texts)

# Convert sentences to sequences
sequences = tokenizer.texts_to_sequences(texts)

print("Word Index:")
print(tokenizer.word_index)

print("\nSequences:")
print(sequences)


# Make all sequences same length


max_length = 4

X = pad_sequences(sequences, maxlen=max_length)

print("\nPadded Sequences:")
print(X)


# Build LSTM model


model = Sequential()

# Embedding layer
# Converts word numbers into dense vectors

model.add(
    Embedding(
        input_dim=len(tokenizer.word_index) + 1,
        output_dim=8,
        input_length=max_length
    )
)

# LSTM layer
# Learns sequence patterns

model.add(LSTM(8))

# Output layer
# Sigmoid gives value between 0 and 1

model.add(Dense(1, activation='sigmoid'))


# Compile model


model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)


# Train model


model.fit(
    X,
    labels,
    epochs=50,
    verbose=1
)

# Test on new sentence


test_text = ["This movie is excellent"]

# Convert to sequence
test_seq = tokenizer.texts_to_sequences(test_text)

# Pad sequence
test_pad = pad_sequences(test_seq, maxlen=max_length)

# Predict
prediction = model.predict(test_pad)

print("\nPrediction:", prediction)

# Convert probability to label
if prediction > 0.5:
    print("Positive Review")
else:
    print("Negative Review")

Word Index:
{'this': 1, 'i': 2, 'movie': 3, 'film': 4, 'very': 5, 'acting': 6, 'story': 7, 'love': 8, 'is': 9, 'amazing': 10, 'good': 11, 'excellent': 12, 'hate': 13, 'terrible': 14, 'boring': 15, 'worst': 16, 'ever': 17}

Sequences:
[[2, 8, 1, 3], [1, 4, 9, 10], [5, 11, 6], [12, 7], [2, 13, 1, 3], [14, 4], [5, 15, 7], [16, 6, 17]]

Padded Sequences:
[[ 2  8  1  3]
 [ 1  4  9 10]
 [ 0  5 11  6]
 [ 0  0 12  7]
 [ 2 13  1  3]
 [ 0  0 14  4]
 [ 0  5 15  7]
 [ 0 16  6 17]]
Epoch 1/50


/Users/swatichandna/.pyenv/versions/3.11.7/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 802ms/step - accuracy: 0.6250 - loss: 0.6929
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6250 - loss: 0.6926
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6250 - loss: 0.6922
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6250 - loss: 0.6918
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6250 - loss: 0.6914
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6250 - loss: 0.6910
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6250 - loss: 0.6906
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6250 - loss: 0.6902
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6250 - loss: 0.6898
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6250 - loss: 0.6894
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6250 - loss: 0.6890
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6250 - loss: 0.6886
Epoch 13/50